[theme]
primaryColor="#1f77b4"          # Button & highlight color
backgroundColor="#f5f7fa"       # Page background
secondaryBackgroundColor="#ffffff"  # Card/sidebar background
textColor="#0e1117"             # Default text
font="inter"               # or "serif", "monospace"
