[theme]
primaryColor="#0f8b8d"          # Button & highlight color
backgroundColor="#dce0d9"       # Page background
secondaryBackgroundColor="#ffffff"  # Card/sidebar background
textColor="#143642"             # Default text
font="inter"               # or "serif", "monospace"
